### ISSUE TITLE
Dead project

### ISSUE THREAD

**Issue by joshuapassos** [fsprojects/oxen#42]
Last commit in 2018. Please, archive the project

**Comment by albertjan** [comment]
@sergey-tihon sorry to bother you, can I just archive this? Or is there something else I should do first?

**Comment by sergey-tihon** [comment]
@albertjan Yes, feel free to archive it if there is no more interest from you and community in this project

**Comment by albertjan** [comment]
I'm interested I just don't have the time/headspace to maintain it. I can leave this open for a month or so to see if someone wants to pick it up.

**Comment by dsyme** [comment]
Archived to https://github.com/fsprojects/zzarchive-oxen
